Function/urls.py
from django.conf.urls import url

from . import views

app_name = 'functifunctionons'

urlpatterns = [
    url(r'^$', views.Home, name='home'),
    url(r'^add/$', views.AddFunction, name='add_function'),
    url(r'^search/$', views.TagSearch, name='tag_search'),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.AllFunction_Tag, name='tag_functions'),
    url(r'^(?P<slug>[\w-]+)/$', views.ShowFunction, name='show_function'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.EditFunction, name='edit_function'),
    url(r'^(?P<slug>[\w-]+)/(?P<tag>[\w-]+)/remove/$', views.RemoveFunction_Tag, name='remove_function_tag'),
]

FunctionsStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('Function.urls', namespace='functions') ),
    path('admin/', admin.site.urls),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Function/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import post_save

import datetime

from random import choice
def randint(n=8):
    return ''.join( [ str(choice([0,1,2,3,4,5,6,7,8,9])) for i in range(n)] )

# Create your models here.
class Function(models.Model):
    """This just handle function data in db"""

    name    = models.CharField(max_length=70)
    content = models.TextField()
    comment = models.TextField()
    tags    = models.CharField(max_length=100)
    slug    = models.CharField(unique= True, blank=True, max_length=100)
    created = models.DateTimeField(auto_now=False, default= datetime.datetime.now)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Function'
        verbose_name_plural = 'Functions'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify( '%s-%s' % ( self.name, randint() ) )
        return super(Function, self).save(*args, **kwargs)

class Tag(models.Model):
    name      = models.CharField(unique=True, max_length=70)
    functions = models.ManyToManyField(Function, blank=True)

    def __str__(self):
        return self.name

from django.core.exceptions import ObjectDoesNotExist
def get_object(Class, **kwargs):
    try:
        return Class.objects.get(**kwargs)
    except ObjectDoesNotExist:
        return None

def attach_func_to_tag(sender, instance, created, **kwargs):
    # if created:
    tags = instance.tags.split(' ')
    for tag in tags:
        ## chk if tag already exist: just add the function 
        ## else create the tag then add the function

        t = get_object(Tag, name= tag)
        if not t:
            t = Tag.objects.create(name= tag)
        t.functions.add(instance)

post_save.connect(attach_func_to_tag, sender=Function)

Function/forms.py
from django import forms

from .models import Function

class FunctionForm(forms.ModelForm):
    """Form definition for Function."""

    class Meta:
        """Meta definition for Functionform."""

        model = Function
        fields = ('name', 'content', 'comment', 'tags')

Function/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse

from .models import Function, Tag
from .forms import FunctionForm

# Create your views here.

def show_functions(request, functions, context={}):
    context.update({'functions': functions})
    return render(request, 'functions.html', context) 

def Home(request):
    ## show all fucntions
    ## in other cases last 20
    functions = Function.objects.all()
    return show_functions(request, functions)



def ShowFunction(request, slug):
    # functions = get_object(Function, slug= slug)
    functions = Function.objects.all().filter(slug= slug)
    context = {'functions': functions}
    return render(request, 'function.html', context) 

def AddFunction(request):
    if request.method == 'POST':
        form = FunctionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('functions:home')

        else:
            return redirect('functions:add_function')

    else:
        form = FunctionForm
        context = {'form': form, 'btn': 'Add'}
        return render(request, 'addfunction_form.html', context)

def get_object(Class, **kwargs):
    try:
        return Class.objects.get(**kwargs)
    except ObjectDoesNotExist:
        return None

def EditFunction(request, slug):
    function = get_object(Function, slug= slug)
    if function:
        if request.method == 'POST':
            form = FunctionForm(request.POST, instance=function)
            if form.is_valid():
                form.save()
                return redirect('functions:home')

            else:
                return redirect('functions:edit_function')

        else:
            form = FunctionForm(instance=function)
            context = {'form': form, 'btn': 'Update', 'slug': slug}
            return render(request, 'addfunction_form.html', context)

    else:
        return HttpResponse('Function Not Found')

def AllFunction_Tag(request, tag):
    ## get data row data from the Tag table
    ## get the clm functions (many to many)
    # then retrieve all the data
    # 
    # i use the lines of home() cuz there are very same
    # the differnce only the functions which sent  
    functions = get_object(Tag, name= tag).functions.all()
    return show_functions(request, functions)

def redirect_prev_page(request):
    previous_path = '/'+ '/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
    return redirect(previous_path)

def RemoveFunction_Tag(request, slug, tag):
    ## i will edit in 2 tables
    ## get the rows
    function    = get_object(Function, slug=slug)
    removed_tag = get_object(Tag, name=tag)

    ## edit the rows to new vals
    new_tags = function.tags.split(' ')
    new_tags.remove(tag)
    new_tags = ' '.join(new_tags) or 'empty_tags'

    function.tags = new_tags
    removed_tag.functions.remove(function)

    ## save the rows
    function.save()
    removed_tag.save()

    return redirect_prev_page(request)
    
def unique(iterable):
    vals = ()
    count = []
    for item in iterable:
        ## exist in list
        try:
            index = vals.index(item)
            count[index] += 1
        ## not exist in list
        except ValueError:
            vals  += (item,)
            count += (1,)
    return vals , count

def TagSearch(request):
    if request.method == 'POST':
        query = request.POST.get('q')
        if query:
            q_tags = query.split(' ')
            functions = ()

            ## get all functions in each tag
            for tag in q_tags:
                tag = get_object(Tag, name= tag)
                if tag:
                    functions += tuple(tag.functions.all())

            ## unique functions and get number of repeatation for each
            functions, counts = unique(functions)

            ## sort them accroding to count number
            functions = tuple([function for _, function in sorted(zip(counts, functions), key= lambda elm: elm[0], reverse=True)])
            
            return show_functions(  request, functions, context={'query_value': request.POST['q']}  )
        
        return HttpResponse('this is wrong query')

    return redirect('functions:home')

def contact(request):
    return render(request, 'contact.html', {})

Function/templates/addfunction_form.html
{% extends "index.html" %}
{% load static %}
{% load myfilters %}
{% block content %}
    
    
    <!-- s-content
    ================================================== -->
    <section class="s-content s-content--narrow">

        <div class="row">
            <div class="col-full s-content__main">

                <form name="cForm" id="cForm" method="post" action="">
                    {% csrf_token %}
                   
                    <fieldset>

                        <div class="form-field">
                            <input name="{{form.name.name}}" type="text" class="full-width" placeholder="Name" value="{{form.name.value | default_if_none:''}}">
                        </div>

                        
                        <div class="form-field">
                            <div class="entry__meta">
                                <span class="entry__meta-links">
                                    {% if btn == 'Update' %}    
                                    {% with form.tags.value|split:' ' as tags %}
                                    {% for tag in tags %}
                                        <div style="background: #FFF; display: inline-block; margin-right: 10px; padding: 5px 13px 5px 10px; border-radius: 5px; position: relative;">
                                            <a class="old-tag" href="{% url 'functions:tag_functions' tag %}" style="margin-right: 10px">{{tag}}</a>
                                            <a href="{% url 'functions:remove_function_tag' slug tag %}" style="color: #333; font-size: .7em; position:absolute; top: 50%; transform: translateY(-50%); margin-right: 5px">x</a>
                                        </div>
                                    {% endfor %}
                                    {% endwith %}
                                    {% endif %}

                                        

                                </span>
                            </div>
                            <input id="new-tags"  name="" type="text" class="full-width" placeholder="tags" value="">
                            <input id="all-tags"  name="{{form.tags.name}}" type="hidden">
                            <script>
                                form = document.getElementById('cForm')
                                form.onsubmit = ()=>{

                                    var AllTags = document.getElementById('all-tags'),
                                        NewTags = document.getElementById('new-tags'),
                                        OldTags = document.getElementsByClassName('old-tag'),
                                        OldTagsTxt = '',
                                        NewTagsTxt = '';
    
                                    for (tag of OldTags){
                                        OldTagsTxt += tag.text + ' '
                                    }
    
                                    NewTagsTxt = NewTags.value
                                    AllTags.value = OldTagsTxt + NewTagsTxt
    
                                    console.log(AllTags.value)
                                }

                            </script>
                        </div>                            

                        <div class="form-field">
                            <input name="{{form.comment.name}}" type="text" class="full-width" placeholder="Comment"  value="{{form.comment.value | default_if_none:''}}">
                        </div>

                        <div class="message form-field">
                        <textarea name="{{form.content.name}}" class="full-width" placeholder="Your Code">{{form.content.value | default_if_none:''}}</textarea>
                        </div>

                        <button type="submit" class="submit btn btn--primary full-width">{{btn}}</button>

                    </fieldset>
                </form> <!-- end form -->


            </div> <!-- end s-content__main -->

        </div> <!-- end row -->

    </section> <!-- s-content -->


{% endblock content %}

Function/templates/function.html
{% extends "index.html" %}
{% load static %}
{% load myfilters %}

{% block content %}
    
    
    <!-- s-content
    ================================================== -->
    <section class="s-content s-content--narrow">

        <div class="row">
            
            {% for function in functions %}
                
            
                
            <div class="s-content__header col-full">
                <h1 class="s-content__header-title">
                    {{function.name}}.
                </h1>
            </div> <!-- end s-content__header -->
    
            <div class="s-content__media col-full">
                <div id="map-wrap">
                    <div id="map-container">
                        {{function.content | replacetabs | safe | linebreaks}}
                    </div>
                </div> 
            </div> <!-- end s-content__media -->

            <div class="col-full s-content__main">

                <p class="lead">
                    Date: {{function.created | date:'jM, Y'}}
                </p>
                
                <p>
                    Comment: {{function.comment}}
                </p>

            </div> <!-- end s-content__main -->

            <!-- func tags -->
            <div class="entry__meta">
                <span class="entry__meta-links">
                    {% for tag in function.tags|split:' ' %}
                        <div style="
                                background: #FFF; 
                                display: 
                                inline-block;  
                                margin-right: 10px; 
                                padding: 5px 13px 5px 10px; 
                                border-radius: 5px; 
                                position: relative;">
                            <a href="{% url 'functions:tag_functions' tag %}" style="margin-right: 10px">{{tag}}</a>
                            <a href="{% url 'functions:remove_function_tag' function.slug tag %}" style="color: #333; font-size: .7em; position:absolute; top: 50%; transform: translateY(-50%); margin-right: 5px">x</a>
                            
                        </div>
                    {% endfor %}
                </span>
            </div>
            {% endfor %}

        </div> <!-- end row -->

    </section> <!-- s-content -->


{% endblock content %}

Function/templates/functions.html
{% extends "index.html" %}
{% load myfilters %}
<style>
    /*
    *{
        padding: 0;
        margin: 3px;
        box-sizing: border-box;
    }
    code{
        display: block
    }
    code > p{
        background: #EEE;
        display: inline-block;
        padding: 5px 7px
    }
    */
</style>

{% block content %}
    
    <style>
        .code__area{
            background-color: #EEE;
            padding: 15px 20px 12px;
            margin: 0 0 24px 0;
            overflow: auto;
        }

        .code__area > p{
            margin: 0;
            white-space: nowrap;
            /*overflow: auto;*/
            font-size: 11px;
            max-height: 250px;
            line-height: 1.3636em;
        }

        .entry__edit{
            text-align: right;
            margin-top: 8px
        }

        .entry__edit > a,
        #add-function > a{
            background-color: rgb(91, 122, 255);
            color: white;
            padding: 5px 10px;
            border-radius: 5px;
        } 
        #add-function{
            margin-bottom: 15px
        }
    </style>

    <section class="s-content">
        <div class="row masonry-wrap">
            <div id="add-function" style="text-align:center;">
                <a href="{% url 'functions:add_function' %}">add_new</a>
            </div>
            <div class="row masonry-wrap">
                <div class="masonry">
                    {% for function in functions %}
                        
                        <article class="masonry__brick entry format-standard" data-aos="fade-up">
                            <div class="entry__text">
                                
                                <!-- funcname | created time -->
                                <div class="entry__header">
                
                                    <div class="entry__date">
                                        <a href="{% url 'functions:show_function' function.slug %}">{{function.created | date:'jM, Y'}}</a>
                                    </div>
                                    <h1 class="entry__title"><a href="{% url 'functions:show_function' function.slug %}">{{function.name}}</a></h1>
                                    
                                </div>
                                
                                <!-- code area -->
                                <div class="code__area">
                                    {{function.content | replacetabs | safe | linebreaks}}
                                </div>

                                <!-- func comment -->
                                <div class="entry__excerpt">
                                    <p>{{function.comment}}</p>
                                </div>

                                <!-- func tags -->
                                <div class="entry__meta">
                                    <span class="entry__meta-links">
                                        {% for tag in function.tags|split:' ' %}
                                            <!--<div style="background: #FF5; display: inline">-->
                                                <a href="{% url 'functions:tag_functions' tag %}">{{tag}}</a>
                                                {% comment %} <a href="{% url 'functions:remove_function_tag' function.slug tag %}">x</a> {% endcomment %}
                                            <!--</div>-->
                                        {% endfor %}
                                    </span>
                                </div>

                                <div class="entry__edit">
                                    <a role="button" href="{% url 'functions:edit_function' function.slug %}">edit</a>
                                </div>


                            </div>
                        </article>

                    {% endfor %}
            
                </div>
            </div>
        </div> <!-- end masonry-wrap -->


        <div class="row">
            <div class="col-full">
                <nav class="pgn">
                    <ul>
                        <li><a class="pgn__prev" href="#0">Prev</a></li>
                        <li><a class="pgn__num" href="#0">1</a></li>
                        <li><span class="pgn__num current">2</span></li>
                        <li><a class="pgn__num" href="#0">3</a></li>
                        <li><a class="pgn__num" href="#0">4</a></li>
                        <li><a class="pgn__num" href="#0">5</a></li>
                        <li><span class="pgn__num dots">…</span></li>
                        <li><a class="pgn__num" href="#0">8</a></li>
                        <li><a class="pgn__next" href="#0">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section> <!-- s-content -->

{% endblock content %}



<!-- not appended -->
{% comment %}
    <a href="{% url 'functions:remove_function_tag' function.slug tag %}">remove-tag</a>
{% endcomment %}

 

    

templates/contact.html
{% extends "index.html" %}
{% load static %}

{% block content %}
    
    
    <!-- s-content
    ================================================== -->
    <section class="s-content s-content--narrow">

        <div class="row">
            <div class="col-full s-content__main">

                <form name="cForm" id="cForm" method="post" action="">
                    <fieldset>

                        <div class="form-field">
                            <input name="cName" type="text" id="cName" class="full-width" placeholder="Your Name" value="">
                        </div>

                        <div class="form-field">
                            <input name="cEmail" type="text" id="cEmail" class="full-width" placeholder="Your Email" value="">
                        </div>

                        <div class="form-field">
                            <input name="cWebsite" type="text" id="cWebsite" class="full-width" placeholder="Website"  value="">
                        </div>

                        <div class="message form-field">
                        <textarea name="cMessage" id="cMessage" class="full-width" placeholder="Your Message" ></textarea>
                        </div>

                        <button type="submit" class="submit btn btn--primary full-width">Submit</button>

                    </fieldset>
                </form> <!-- end form -->


            </div> <!-- end s-content__main -->

        </div> <!-- end row -->

    </section> <!-- s-content -->


{% endblock content %}







templates/index.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    {% load static %}

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Code-Market</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

</head>

<body id="top">

    <!-- pageheader
    ================================================== -->
    <section class="s-pageheader s-pageheader--home">

        <header class="header">
            <div class="header__content row">

                <div class="header__logo">
                    <a class="logo" href="{% url 'functions:home' %}">
                        <img src="{% static 'images/logo.svg' %}" alt="Homepage">
                    </a>
                </div> <!-- end header__logo -->

                <a class="header__search-trigger" href="#0"></a>
                <div class="header__search">

                    <form role="search" method="post" class="header__search-form" action="{% url 'functions:tag_search' %}">
                        {% csrf_token %}
                        <label>
                            <span class="hide-content">Search for:</span>
                            <input type="search" class="search-field" placeholder="Type Keywords" value="{{query_value}}" name="q" title="Search for:" autocomplete="off" required="">
                        </label>
                        <input type="submit" class="search-submit" value="Search">
                    </form>
                    <a href="#0" title="Close Search" class="header__overlay-close">Close</a>

                </div>  <!-- end header__search -->

                
            </div> <!-- header-content -->
        </header> <!-- header -->

    </section> <!-- end s-pageheader -->


    
    {% block content %}
        
    {% endblock content %}
        


    <!-- s-footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">
                
                <div class="col-five md-full end s-footer__subscribe">
                        
                    <h4>Our Newsletter</h4>

                    <p>Sit vel delectus amet officiis repudiandae est voluptatem. Tempora maxime provident nisi et fuga et enim exercitationem ipsam. Culpa consequatur occaecati.</p>

                    <div class="subscribe-form">
                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="EMAIL" class="email" id="mc-email" placeholder="Email Address" required="">
                
                            <input type="submit" name="subscribe" value="Send">
                
                            <label for="mc-email" class="subscribe-message"></label>
                
                        </form>
                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div>
        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="col-full">
                    <div class="s-footer__copyright">
                        <span>© Copyright Philosophy 2018</span> 
                        <span>Site Template by <a href="https://colorlib.com/">Colorlib</a></span>
                    </div>

                    <div class="go-top">
                        <a class="smoothscroll" title="Back to Top" href="#top"></a>
                    </div>
                </div>
            </div>
        </div> <!-- end s-footer__bottom -->

    </footer> <!-- end s-footer -->


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader">
            <div class="line-scale">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>